/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPKG;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import oracle.jdbc.OracleDriver;
import javax.swing.DefaultListModel;
import oracle.jdbc.OracleTypes;
/**
 *
 * @author david
 */
public class Add_Modify_Salle extends javax.swing.JFrame {

    Main_Screen main_Page = null;
    Connection conn = null;
    /**
     * Creates new form Add_Modify_Salle
     */
    public Add_Modify_Salle(Connection conn_Main, Main_Screen main, String template) {
        initComponents();
        conn = conn_Main;
        jLabel1.setText("Salles-" + template);
        main_Page = main;
        Set_List();
    }
    public void Set_List()
    {
        DefaultListModel dlm = new DefaultListModel();
        ResultSet rst = null;
        Statement stm = null;
        try{
            CallableStatement cstm = conn.prepareCall("{call AMINAPP.SHOWSALLES (?)}");
            cstm.registerOutParameter(1, OracleTypes.CURSOR);
            cstm.execute();
            rst = (ResultSet)cstm.getObject(1);
            
            while(rst.next())
            {
                dlm.addElement(rst.getInt("NUMSALLE"));
            }
            
            cstm.clearParameters();
            cstm.close();
            rst.close();
        }
        catch(SQLException exp){
        }
        
        List.setModel(dlm);
    }
    public Add_Modify_Salle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXB_Adresse = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXB_Nom = new javax.swing.JTextField();
        BTN_Accepter = new javax.swing.JButton();
        BTN_Cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Page Title (Add/Modify)");

        jLabel2.setText("Adresse :");

        jLabel3.setText("Nom :");

        BTN_Accepter.setText("Accepter");
        BTN_Accepter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AccepterActionPerformed(evt);
            }
        });

        BTN_Cancel.setText("Cancel");
        BTN_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CancelActionPerformed(evt);
            }
        });

        List.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(List);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXB_Adresse)
                            .addComponent(TXB_Nom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_Accepter, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(BTN_Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXB_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Accepter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXB_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AccepterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AccepterActionPerformed
        if(jLabel1.getText().endsWith("Add"))
        {
            try{
                CallableStatement Callins = conn.prepareCall("{call AMINAPP.ADDSALLES (?,?)}");
                Callins.setString(1, TXB_Adresse.getText());
                Callins.setString(2, TXB_Nom.getText());

                Callins.executeUpdate();
                Callins.clearParameters();
                Callins.close();
            }
            catch(SQLException ins)
            {
                System.out.println(ins.getMessage());
            }
        }
        else
        {
            try{
                CallableStatement Callins = conn.prepareCall("{call AMINAPP.UPDATESALLES (?,?,?)}");
                Callins.setInt(1, Integer.parseInt(List.getSelectedValue().toString()));
                Callins.setString(2, TXB_Adresse.getText());
                Callins.setString(3, TXB_Nom.getText());

                Callins.executeUpdate();
                Callins.clearParameters();
                Callins.close();
            }
            catch(SQLException ins)
            {
                System.out.println(ins.getMessage());
            }
        }
        
        Set_List();
    }//GEN-LAST:event_BTN_AccepterActionPerformed

    private void BTN_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CancelActionPerformed
        main_Page.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_CancelActionPerformed

    private void ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMouseClicked
        if(jLabel1.getText().endsWith("Modify"))
        {
            try{
                ResultSet rst = null;
                CallableStatement cstm = conn.prepareCall("{call AMINAPP.SHOWSALLE (?,?)}");
                cstm.setInt(1, Integer.parseInt(String.valueOf(List.getSelectedValue().toString().subSequence(List.getSelectedValue().toString().lastIndexOf("-")+1, List.getSelectedValue().toString().length()))));
                cstm.registerOutParameter(2, OracleTypes.CURSOR);
                cstm.execute();
                rst = (ResultSet)cstm.getObject(2);
                
                rst.next();
                
                TXB_Adresse.setText(rst.getString("ADRESSE"));
                TXB_Nom.setText(rst.getString("NOMSALLE"));

                rst.close();
                cstm.clearParameters();
                cstm.close();
            }
            catch(SQLException sqe){
            }
        }
    }//GEN-LAST:event_ListMouseClicked

    private void ListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Modify_Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Modify_Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Modify_Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Modify_Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Modify_Salle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Accepter;
    private javax.swing.JButton BTN_Cancel;
    private javax.swing.JList List;
    private javax.swing.JTextField TXB_Adresse;
    private javax.swing.JTextField TXB_Nom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
